url: https://hackseq.github.io
baseurl: /jekyll-theme-windows95

# variables
title: hackseq18
description: genomics hackath0n

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE", "Gemfile", "Gemfile.lock", "jekyll-theme-windows95.gemspec"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
highlighter: rouge
# excerpt_separator: "\n\n"
